package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.buildSteps.script
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'Build'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("Build")) {
    expectSteps {
        step {
            name = "NPM install"
            type = "jonnyzzz.npm"
            param("npm_commands", "install")
        }
    }
    steps {
        insert(1) {
            script {
                name = "node version check"
                scriptContent = "node -v"
            }
        }
    }
}
