package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.triggers.vcs
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'Build'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("Build")) {
    check(name == "Build") {
        "Unexpected name: '$name'"
    }
    name = "build"

    expectSteps {
        step {
            name = "NPM install"
            type = "jonnyzzz.npm"
            param("npm_commands", "install")
        }
    }
    steps {
        items.removeAt(0)
    }

    triggers {
        remove {
            vcs {
                branchFilter = ""
                perCheckinTriggering = true
                enableQueueOptimization = false
            }
        }
    }
}
