package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.buildSteps.ScriptBuildStep
import jetbrains.buildServer.configs.kotlin.v2019_2.buildSteps.script
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'ExpressApp'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("ExpressApp")) {
    expectSteps {
        step {
            name = "Run Test"
            type = "jonnyzzz.npm"
            param("npm_commands", """
                install
                test
            """.trimIndent())
        }
        script {
            name = "testing"
            scriptContent = """
                npm install cucumber-teamcity-formatter --save
                ./node_modules/.bin/cucumber-js --format node_modules/cucumber-teamcity-formatter
            """.trimIndent()
        }
    }
    steps {
        update<ScriptBuildStep>(1) {
            scriptContent = """
                npm install cucumber-teamcity-formatter --save-dev
                ./node_modules/.bin/cucumber-js --format node_modules/cucumber-teamcity-formatter
            """.trimIndent()
        }
    }
}
